'use strict';

const fs = require('fs');
const net = require('net');
const path = require('path');
const { spawn, execFile } = require('child_process');
const { app, BrowserWindow, Menu, dialog, ipcMain, session } = require('electron');
const state = require('./app-state');
const logger = require('../logger');

const PARTITION = 'persist:anixapp-youtube-cookies';
const LOGIN_URL =
  'https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F&hl=ru';
const YOUTUBE_HOME = 'https://www.youtube.com/';
const TIMEOUT_MS = 15 * 60 * 1000;

/** @type {import('electron').BrowserWindow | null} */
let loginWindow = null;
/** @type {import('electron').BrowserWindow | null} */
let waitWindow = null;
/** @type {Array<(value: unknown) => void>} */
let pendingResolves = [];
let harvesting = false;
let systemLoginActive = false;

function chromeUserAgent() {
  const ver = String(process.versions.chrome || '120.0.0.0');
  if (process.platform === 'darwin') {
    return `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${ver} Safari/537.36`;
  }
  if (process.platform === 'linux') {
    return `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${ver} Safari/537.36`;
  }
  return `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${ver} Safari/537.36`;
}

function isRelevantDomain(domain) {
  const host = String(domain || '').replace(/^#HttpOnly_/i, '').replace(/^\./, '').toLowerCase();
  return (
    host === 'youtube.com'
    || host.endsWith('.youtube.com')
    || host === 'youtu.be'
    || host.endsWith('.youtu.be')
    || host === 'youtube-nocookie.com'
    || host.endsWith('.youtube-nocookie.com')
    || host === 'google.com'
    || host.endsWith('.google.com')
    || host === 'googlevideo.com'
    || host.endsWith('.googlevideo.com')
    || host === 'gstatic.com'
    || host.endsWith('.gstatic.com')
    || host === 'googleapis.com'
    || host.endsWith('.googleapis.com')
    || host === 'googleusercontent.com'
    || host.endsWith('.googleusercontent.com')
    || host === 'ggpht.com'
    || host.endsWith('.ggpht.com')
  );
}

function escapeNetscapeValue(value) {
  return String(value ?? '').replace(/[\t\r\n]/g, '');
}

/**
 * @param {Array<{ name?: string, value?: string, domain?: string, hostOnly?: boolean, path?: string, secure?: boolean, httpOnly?: boolean, session?: boolean, expirationDate?: number }>} cookies
 */
function cookiesToNetscape(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by AnixApp for yt-dlp. Do not share it.',
    '',
  ];
  for (const cookie of cookies) {
    if (!cookie || !cookie.name || !isRelevantDomain(cookie.domain)) continue;
    let domain = String(cookie.domain || '');
    if (!domain) continue;
    const hostOnly = !!cookie.hostOnly;
    if (!hostOnly && !domain.startsWith('.')) domain = `.${domain}`;
    const includeSub = !hostOnly && domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.session || !cookie.expirationDate
      ? 0
      : Math.max(0, Math.floor(Number(cookie.expirationDate)));
    const pathName = cookie.path || '/';
    const name = escapeNetscapeValue(cookie.name);
    const value = escapeNetscapeValue(cookie.value);
    const domainField = cookie.httpOnly ? `#HttpOnly_${domain}` : domain;
    lines.push([domainField, includeSub, pathName, secure, String(expires), name, value].join('\t'));
  }
  return `${lines.join('\n')}\n`;
}

/**
 * @param {Array<{ name?: string, domain?: string }>} cookies
 */
function isLoggedIn(cookies) {
  const names = new Set(
    cookies
      .filter((c) => isRelevantDomain(c.domain))
      .map((c) => c.name)
  );
  if (names.has('LOGIN_INFO')) return true;
  if (names.has('SAPISID') && (names.has('SID') || names.has('__Secure-1PSID'))) return true;
  if (names.has('__Secure-1PSID') && names.has('__Secure-3PSID')) return true;
  return false;
}

function parentWindow() {
  if (state.adminPanelWindow && !state.adminPanelWindow.isDestroyed()) return state.adminPanelWindow;
  if (state.mainWindow && !state.mainWindow.isDestroyed()) return state.mainWindow;
  return null;
}

function showBox(opts) {
  const parent = parentWindow();
  return parent ? dialog.showMessageBox(parent, opts) : dialog.showMessageBox(opts);
}

function waitForBrowserDone(browserName) {
  return new Promise((resolve) => {
    if (waitWindow && !waitWindow.isDestroyed()) {
      try { waitWindow.close(); } catch { /* ignore */ }
    }
    let settled = false;
    const onDone = () => finish('done');
    const onCancel = () => finish('cancel');
    const finish = (value) => {
      if (settled) return;
      settled = true;
      ipcMain.removeListener('youtube-wait:done', onDone);
      ipcMain.removeListener('youtube-wait:cancel', onCancel);
      const win = waitWindow;
      waitWindow = null;
      if (win && !win.isDestroyed()) {
        try { win.close(); } catch { /* ignore */ }
      }
      resolve(value);
    };
    ipcMain.on('youtube-wait:done', onDone);
    ipcMain.on('youtube-wait:cancel', onCancel);

    const win = new BrowserWindow({
      width: 440,
      height: 240,
      resizable: false,
      minimizable: false,
      maximizable: false,
      fullscreenable: false,
      autoHideMenuBar: true,
      modal: false,
      show: false,
      title: 'Вход в YouTube',
      backgroundColor: '#141414',
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        sandbox: true,
        preload: path.join(__dirname, '..', 'youtube-wait-preload.js'),
      },
    });
    waitWindow = win;
    win.setMenuBarVisibility(false);
    win.on('closed', () => finish('cancel'));
    win.once('ready-to-show', () => {
      try { win.showInactive(); } catch { win.show(); }
    });
    win.loadFile(path.join(__dirname, '..', 'youtube-wait.html'), {
      query: { browser: browserName },
    }).catch(() => finish('cancel'));
  });
}

function finishPending(result) {
  harvesting = false;
  systemLoginActive = false;
  const resolvers = pendingResolves;
  pendingResolves = [];
  const win = loginWindow;
  loginWindow = null;
  const wait = waitWindow;
  waitWindow = null;
  if (win && !win.isDestroyed()) {
    try { win.close(); } catch { /* ignore */ }
  }
  if (wait && !wait.isDestroyed()) {
    try { wait.close(); } catch { /* ignore */ }
  }
  for (const resolve of resolvers) resolve(result);
}

function fromCdpCookie(cookie) {
  const domain = String(cookie?.domain || '');
  const expires = Number(cookie?.expires);
  const sessionCookie = cookie?.session === true || !Number.isFinite(expires) || expires <= 0;
  return {
    name: String(cookie?.name || ''),
    value: String(cookie?.value || ''),
    domain,
    hostOnly: !domain.startsWith('.'),
    path: cookie?.path || '/',
    secure: !!cookie?.secure,
    httpOnly: !!cookie?.httpOnly,
    session: sessionCookie,
    expirationDate: sessionCookie ? undefined : expires,
  };
}

function summarizeCookies(cookies) {
  const relevant = cookies.filter((c) => isRelevantDomain(c.domain));
  return {
    cookies_txt: cookiesToNetscape(relevant),
    cookieCount: relevant.length,
    loggedIn: isLoggedIn(relevant),
  };
}

function findSystemChromium() {
  const local = process.env.LOCALAPPDATA || '';
  const pf = process.env.PROGRAMFILES || 'C:\\Program Files';
  const pf86 = process.env['PROGRAMFILES(X86)'] || 'C:\\Program Files (x86)';
  /** @type {string[]} */
  const candidates = [];
  if (process.platform === 'win32') {
    candidates.push(
      path.join(pf, 'Google', 'Chrome', 'Application', 'chrome.exe'),
      path.join(pf86, 'Google', 'Chrome', 'Application', 'chrome.exe'),
      path.join(local, 'Google', 'Chrome', 'Application', 'chrome.exe'),
      path.join(pf, 'Microsoft', 'Edge', 'Application', 'msedge.exe'),
      path.join(pf86, 'Microsoft', 'Edge', 'Application', 'msedge.exe'),
      path.join(local, 'Microsoft', 'Edge', 'Application', 'msedge.exe'),
    );
  } else if (process.platform === 'darwin') {
    candidates.push(
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
    );
  } else {
    candidates.push(
      '/usr/bin/google-chrome-stable',
      '/usr/bin/google-chrome',
      '/usr/bin/chromium-browser',
      '/usr/bin/chromium',
      '/snap/bin/chromium',
      '/usr/bin/microsoft-edge',
      '/usr/bin/microsoft-edge-stable',
    );
  }
  return candidates.find((p) => {
    try { return fs.existsSync(p); } catch { return false; }
  }) || null;
}

function getFreePort() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.unref();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const addr = server.address();
      const port = addr && typeof addr === 'object' ? addr.port : 0;
      server.close((err) => {
        if (err) reject(err);
        else resolve(port);
      });
    });
  });
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function waitForCdp(port, timeoutMs = 25000) {
  const started = Date.now();
  let lastErr = 'нет ответа';
  while (Date.now() - started < timeoutMs) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/json/version`);
      if (res.ok) return await res.json();
      lastErr = `HTTP ${res.status}`;
    } catch (err) {
      lastErr = err instanceof Error ? err.message : String(err);
    }
    await sleep(250);
  }
  throw new Error(`браузер не ответил (${lastErr})`);
}

/**
 * @param {string} wsUrl
 */
function openCdp(wsUrl) {
  return new Promise((resolve, reject) => {
    if (typeof WebSocket === 'undefined') {
      reject(new Error('WebSocket недоступен в этой сборке Electron'));
      return;
    }
    const ws = new WebSocket(wsUrl);
    let nextId = 0;
    const pending = new Map();
    const timer = setTimeout(() => {
      try { ws.close(); } catch { /* ignore */ }
      reject(new Error('таймаут CDP'));
    }, 8000);

    ws.addEventListener('open', () => {
      clearTimeout(timer);
      resolve({
        send(method, params) {
          return new Promise((res, rej) => {
            const id = ++nextId;
            pending.set(id, { res, rej });
            try {
              ws.send(JSON.stringify({ id, method, params }));
            } catch (err) {
              pending.delete(id);
              rej(err instanceof Error ? err : new Error(String(err)));
            }
          });
        },
        close() {
          try { ws.close(); } catch { /* ignore */ }
        },
      });
    });
    ws.addEventListener('message', (ev) => {
      let msg;
      try { msg = JSON.parse(String(ev.data)); } catch { return; }
      const waiter = pending.get(msg.id);
      if (!waiter) return;
      pending.delete(msg.id);
      if (msg.error) waiter.rej(new Error(msg.error.message || 'CDP error'));
      else waiter.res(msg.result || {});
    });
    ws.addEventListener('error', () => {
      clearTimeout(timer);
      reject(new Error('не удалось подключиться к браузеру'));
    });
  });
}

/**
 * @param {number} port
 */
async function collectCookiesFromCdp(port) {
  const version = await waitForCdp(port, 4000);
  const browserWs = String(version?.webSocketDebuggerUrl || '');
  if (browserWs) {
    const cdp = await openCdp(browserWs);
    try {
      const result = await cdp.send('Storage.getCookies');
      if (Array.isArray(result?.cookies)) {
        return result.cookies.map(fromCdpCookie);
      }
    } catch {
      try {
        const result = await cdp.send('Network.getAllCookies');
        if (Array.isArray(result?.cookies)) {
          return result.cookies.map(fromCdpCookie);
        }
      } catch {
        /* try page target below */
      }
    } finally {
      cdp.close();
    }
  }

  const listRes = await fetch(`http://127.0.0.1:${port}/json/list`);
  const targets = listRes.ok ? await listRes.json() : [];
  const page = Array.isArray(targets)
    ? targets.find((t) => t && t.type === 'page' && t.webSocketDebuggerUrl)
    : null;
  if (!page?.webSocketDebuggerUrl) {
    throw new Error('не удалось прочитать куки из браузера');
  }
  const pageCdp = await openCdp(page.webSocketDebuggerUrl);
  try {
    await pageCdp.send('Network.enable').catch(() => {});
    const result = await pageCdp.send('Network.getAllCookies');
    return Array.isArray(result?.cookies) ? result.cookies.map(fromCdpCookie) : [];
  } finally {
    pageCdp.close();
  }
}

function killProcessTree(proc) {
  if (!proc || proc.killed || proc.exitCode != null) return;
  const pid = proc.pid;
  if (process.platform === 'win32' && pid) {
    execFile('taskkill', ['/pid', String(pid), '/T', '/F'], () => {});
    return;
  }
  try { proc.kill('SIGTERM'); } catch { /* ignore */ }
}

async function closeSystemBrowser(proc, port) {
  try {
    const version = await waitForCdp(port, 1500);
    const wsUrl = String(version?.webSocketDebuggerUrl || '');
    if (wsUrl) {
      const cdp = await openCdp(wsUrl);
      try { await cdp.send('Browser.close'); } catch { /* ignore */ }
      cdp.close();
      await sleep(400);
    }
  } catch {
    /* already gone */
  }
  killProcessTree(proc);
}

function spawnSystemChromium(exe, port, userDataDir) {
  const args = [
    `--user-data-dir=${userDataDir}`,
    `--remote-debugging-port=${port}`,
    '--remote-debugging-address=127.0.0.1',
    '--remote-allow-origins=*',
    '--no-first-run',
    '--no-default-browser-check',
    '--new-window',
    LOGIN_URL,
  ];
  if (process.platform === 'linux') args.unshift('--password-store=basic');
  logger.info('youtube-login', 'spawn system browser', { exe, port });
  return spawn(exe, args, {
    stdio: 'ignore',
    windowsHide: false,
  });
}

async function collectElectronCookies() {
  const ses = session.fromPartition(PARTITION);
  try {
    await ses.cookies.flushStore();
  } catch {
    /* ignore */
  }
  const cookies = await ses.cookies.get({});
  return summarizeCookies(cookies);
}

async function openSystemBrowserLogin(exe) {
  const port = await getFreePort();
  if (!port) throw new Error('нет свободного порта для браузера');
  const userDataDir = path.join(app.getPath('userData'), 'youtube-login-profile');
  fs.mkdirSync(userDataDir, { recursive: true });

  const proc = spawnSystemChromium(exe, port, userDataDir);
  let closedByUs = false;

  const onProcExit = () => {
    if (closedByUs || !systemLoginActive) return;
    finishPending({ ok: false, cancelled: true });
  };
  proc.once('error', (err) => {
    finishPending({
      ok: false,
      error: err instanceof Error ? err.message : 'не удалось запустить Chrome / Edge',
    });
  });
  proc.once('exit', onProcExit);

  try {
    await waitForCdp(port);
  } catch (err) {
    closedByUs = true;
    killProcessTree(proc);
    throw err;
  }

  const timer = setTimeout(() => {
    closedByUs = true;
    void closeSystemBrowser(proc, port);
    finishPending({ ok: false, error: 'Время входа в YouTube истекло' });
  }, TIMEOUT_MS);

  const browserName = /msedge/i.test(exe) ? 'Edge' : 'Chrome';
  try {
    while (systemLoginActive) {
      const action = await waitForBrowserDone(browserName);
      if (!systemLoginActive) return;
      if (action !== 'done') {
        closedByUs = true;
        clearTimeout(timer);
        await closeSystemBrowser(proc, port);
        finishPending({ ok: false, cancelled: true });
        return;
      }
      let harvested;
      try {
        harvested = summarizeCookies(await collectCookiesFromCdp(port));
      } catch (err) {
        if (!systemLoginActive) return;
        await showBox({
          type: 'warning',
          buttons: ['Понятно'],
          defaultId: 0,
          title: 'YouTube',
          message: 'Не удалось прочитать сессию из браузера.',
          detail: err instanceof Error ? err.message : String(err),
        });
        continue;
      }
      if (!harvested.loggedIn) {
        await showBox({
          type: 'warning',
          buttons: ['Понятно'],
          defaultId: 0,
          title: 'YouTube',
          message: 'Сначала войдите в аккаунт Google / YouTube, затем нажмите «Готово».',
        });
        continue;
      }
      closedByUs = true;
      clearTimeout(timer);
      await closeSystemBrowser(proc, port);
      finishPending({ ok: true, ...harvested });
      return;
    }
  } catch (err) {
    closedByUs = true;
    clearTimeout(timer);
    await closeSystemBrowser(proc, port);
    finishPending({
      ok: false,
      error: err instanceof Error ? err.message : 'не удалось получить куки YouTube',
    });
  }
}

async function harvestElectronAndFinish() {
  const win = loginWindow;
  if (!win || win.isDestroyed()) {
    finishPending({ ok: false, cancelled: true });
    return;
  }
  if (harvesting) return;
  harvesting = true;
  try {
    try {
      await win.loadURL(YOUTUBE_HOME);
      await sleep(1200);
    } catch {
      /* still try current cookies */
    }
    const harvested = await collectElectronCookies();
    if (!harvested.loggedIn) {
      harvesting = false;
      if (!win.isDestroyed()) {
        await dialog.showMessageBox(win, {
          type: 'warning',
          buttons: ['Понятно'],
          defaultId: 0,
          title: 'YouTube',
          message: 'Сначала войдите в аккаунт Google / YouTube, затем нажмите «Готово».',
        });
      }
      return;
    }
    finishPending({ ok: true, ...harvested });
  } catch (err) {
    harvesting = false;
    finishPending({
      ok: false,
      error: err instanceof Error ? err.message : 'не удалось прочитать куки YouTube',
    });
  }
}

function openElectronYoutubeWindow() {
  const ua = chromeUserAgent();
  const win = new BrowserWindow({
    width: 980,
    height: 760,
    minWidth: 640,
    minHeight: 520,
    parent: undefined,
    modal: false,
    show: true,
    autoHideMenuBar: false,
    title: 'YouTube — после входа: меню «Готово»',
    backgroundColor: '#0f0f0f',
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      partition: PARTITION,
    },
  });
  loginWindow = win;

  try {
    win.webContents.setUserAgent(ua);
    win.webContents.session.setUserAgent(ua);
  } catch {
    /* ignore */
  }

  const menu = Menu.buildFromTemplate([
    {
      label: 'Готово',
      click: () => { void harvestElectronAndFinish(); },
    },
    {
      label: 'Отмена',
      click: () => finishPending({ ok: false, cancelled: true }),
    },
  ]);
  win.setMenu(menu);
  win.setMenuBarVisibility(true);

  win.webContents.setWindowOpenHandler(() => ({
    action: 'allow',
    overrideBrowserWindowOptions: {
      parent: win,
      webPreferences: {
        partition: PARTITION,
        nodeIntegration: false,
        contextIsolation: true,
        sandbox: true,
      },
    },
  }));

  win.webContents.on('did-create-window', (child) => {
    try { child.webContents.setUserAgent(ua); } catch { /* ignore */ }
  });

  const timer = setTimeout(() => {
    finishPending({ ok: false, error: 'Время входа в YouTube истекло' });
  }, TIMEOUT_MS);

  win.on('closed', () => {
    clearTimeout(timer);
    harvesting = false;
    loginWindow = null;
    const resolvers = pendingResolves;
    pendingResolves = [];
    for (const next of resolvers) next({ ok: false, cancelled: true });
  });

  win.loadURL(LOGIN_URL).catch(() => {
    finishPending({ ok: false, error: 'Не удалось открыть страницу входа YouTube' });
  });

  void showBox({
    type: 'info',
    buttons: ['Понятно'],
    defaultId: 0,
    title: 'YouTube',
    message: 'Если Google напишет, что браузер небезопасен — закройте окно и установите Chrome или Edge.',
    detail: 'Встроенное окно приложения Google часто блокирует. Надёжный вход — через системный браузер.',
  }).catch(() => {});
}

function openYoutubeLoginWindow() {
  if (systemLoginActive || (loginWindow && !loginWindow.isDestroyed())) {
    if (loginWindow && !loginWindow.isDestroyed()) loginWindow.focus();
    return new Promise((resolve) => {
      pendingResolves.push(resolve);
    });
  }

  return new Promise((resolve) => {
    pendingResolves.push(resolve);
    const exe = findSystemChromium();
    if (exe) {
      systemLoginActive = true;
      void openSystemBrowserLogin(exe).catch((err) => {
        if (!pendingResolves.length && !systemLoginActive) return;
        finishPending({
          ok: false,
          error: err instanceof Error ? err.message : 'не удалось открыть Chrome / Edge',
        });
      });
      return;
    }
    logger.warn('youtube-login', 'no system chrome/edge, falling back to Electron window');
    openElectronYoutubeWindow();
  });
}

module.exports = { openYoutubeLoginWindow };
